### ISSUE TITLE
fasterrandom crashing on startup

### ISSUE THREAD

**Issue by Justin-J-Morgan** [bigchadguys/bcgplus#33]
![image](https://github.com/bigchadguys/bcgplus/assets/41969108/f80dad40-0e34-46bc-a144-35d4c05f0786)

A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'faster-random'!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'faster-random'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160)
	... 2 more
	Suppressed: java.lang.ExceptionInInitializerError
		at net.minecraft.class_5819.handler$eig000$faster-random$fasterrandom$createThreadSafeInject(class_5819.java:527)
		at net.minecraft.class_5819.method_43050(class_5819.java)
		at net.minecraft.class_3532.<clinit>(class_3532.java:42)
		at net.minecraft.class_156.method_28122(class_156.java:138)
		at net.minecraft.class_156.<clinit>(class_156.java:85)
		at me.jellysquid.mods.sodium.client.util.workarounds.probe.GraphicsAdapterProbe.findAdapters(GraphicsAdapterProbe.java:26)
		at me.jellysquid.mods.sodium.client.SodiumPreLaunch.onPreLaunch(SodiumPreLaunch.java:11)
		at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
		... 3 more
	Caused by: java.lang.IllegalArgumentException: No implementation of the random number generator algorithm "L64X128MixRandom" is available
		at java.base/java.util.random.RandomGeneratorFactory.findProvider(Unknown Source)
		at java.base/java.util.random.RandomGeneratorFactory.factoryOf(Unknown Source)
		at java.base/java.util.random.RandomGeneratorFactory.of(Unknown Source)
		at com.github.anopensaucedev.fasterrandom.util.math.random.RandomGeneratorRandom.<clinit>(RandomGeneratorRandom.java:13)
		... 11 more
Caused by: java.lang.RuntimeException: [Faster Random] This JVM does not implement RandomGeneratorFactory and/or L64X128MixRandom!
	at com.github.anopensaucedev.fasterrandom.FasterRandomPreLaunch.onPreLaunch(FasterRandomPreLaunch.java:18)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	... 3 more

**Comment by jflec** [comment]
FasterRandom has been removed, thanks for the report!
