### ISSUE TITLE
Wrong version of End's Delight is being used

### ISSUE THREAD

**Issue by SpikyStars** [bigchadguys/bcgplus#65]
The version of End's Delight being used in the modpack (at least the version with Cobblemon in it, which is what I'm playing on) is `ends_delight-fabric-1.20.1-2.1`; however, this is the version matching the deprecated Fabric version of Farmer's Delight, and not Farmer's Delight Refabricated which is what the modpack is using.

The version that should instead be used with Farmer's Delight Refabricated is `ends_delight-refabricated-1.20.1-2.1`.

This causes the End Stove from the mod to be unusable in the modpack currently, as it attempts to reference the deprecated Farmer's Delight, producing the following ticking entity crash:
```
java.lang.NoClassDefFoundError: com/nhoryzon/mc/farmersdelight/util/MathUtils
	at knot//cn.foggyhillside.ends_delight.blockentity.EndStoveBlockEntity.cookAndDrop(EndStoveBlockEntity.java:190)
	at knot//cn.foggyhillside.ends_delight.blockentity.EndStoveBlockEntity.tick(EndStoveBlockEntity.java:96)
	at knot//net.minecraft.class_2818$class_5563.mixinextras$bridge$tick$11(class_2818.java)
	at knot//com.bawnorton.neruina.handler.TickHandler.safelyTickBlockEntity(TickHandler.java:169)
	at knot//net.minecraft.class_2818$class_5563.wrapOperation$hoj000$neruina$catchTickingBlockEntity$notTheCauseOfTickLag(class_2818.java:1287)
	at knot//net.minecraft.class_2818$class_5563.method_31703(class_2818.java:662)
	at knot//net.minecraft.class_2818$class_5564.method_31703(class_2818.java:716)
	at knot//net.minecraft.class_1937.method_18471(class_1937.java:470)
	at knot//net.minecraft.class_3218.method_18765(class_3218.java:390)
	at knot//net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at knot//net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at knot//net.minecraft.class_1132.method_3748(class_1132.java:105)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: com.nhoryzon.mc.farmersdelight.util.MathUtils
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 15 more
```

**Comment by jflec** [comment]
Thanks for the heads up! Will make to include a fix next update.
