### ISSUE TITLE
DecoderException Error on Raid

### ISSUE THREAD

**Issue by ac15CR** [bigchadguys/bcgplus#71]
I started a raid then shortly after received this error. This area can now not be loaded or it causes a client disconnect. It does not crash the server just disconnects the client. The server gives no additional information and players must be tped out before loading in to prevent them from disconnecting.

Client log error found below:

`io.netty.handler.codec.DecoderException: com.google.gson.JsonParseException: Don't know how to turn {"color":"white"} into a Component
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:489) ~[netty-codec-4.1.82.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:280) ~[netty-codec-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336) ~[netty-codec-4.1.82.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308) ~[netty-codec-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336) ~[netty-codec-4.1.82.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) ~[netty-codec-4.1.82.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:444) ~[netty-codec-4.1.82.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:280) ~[netty-codec-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[netty-codec-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[netty-handler-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.82.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.82.Final.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: com.google.gson.JsonParseException: Don't know how to turn {"color":"white"} into a Component
	at net.minecraft.class_2561$class_2562.method_10871(class_2561.java:240) ~[client-intermediary.jar:?]
	at net.minecraft.class_2561$class_2562.deserialize(class_2561.java:152) ~[client-intermediary.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar:?]
	at net.minecraft.class_3518.method_47993(class_3518.java:524) ~[client-intermediary.jar:?]
	at net.minecraft.class_3518.method_47994(class_3518.java:568) ~[client-intermediary.jar:?]
	at net.minecraft.class_2561$class_2562.method_10877(class_2561.java:401) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_10808(class_2540.java:506) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_37436(class_2540.java:310) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540$class_7461.method_43828(class_2540.java:1789) ~[client-intermediary.jar:?]
	at net.minecraft.class_2941$1.method_12716(class_2941.java:35) ~[client-intermediary.jar:?]
	at net.minecraft.class_2945$class_7834.method_46363(class_2945.java:240) ~[client-intermediary.jar:?]
	at net.minecraft.class_2945$class_7834.method_46362(class_2945.java:236) ~[client-intermediary.jar:?]
	at net.minecraft.class_2739.method_46616(class_2739.java:32) ~[client-intermediary.jar:?]
	at net.minecraft.class_2739.<init>(class_2739.java:16) ~[client-intermediary.jar:?]
	at net.minecraft.class_2539$class_4532.method_22310(class_2539.java:459) ~[client-intermediary.jar:?]
	at net.minecraft.class_2539.method_10783(class_2539.java:522) ~[client-intermediary.jar:?]
	at net.minecraft.class_2543.decode(class_2543.java:32) ~[client-intermediary.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:519) ~[netty-codec-4.1.82.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:458) ~[netty-codec-4.1.82.Final.jar:?]
	... 36 more`

**Comment by AeriusOhara** [comment]
I had this same issue just now. Waypointed to a village with a debuff I forgot I had which prompted a raid. Midway through the raid I waypointed back to my base to grab a horn that'd show the ones hiding or behind walls only to waypoint back to the village and receive the error.

I fixed it by opening my player file and setting my position to my spawn's which got me out of reach of whatever caused it. But whenever I go back to that village the error happens again and persists like before.

I'm not sure if I'm supposed to post the log here, or if I can [link to it](https://mclo.gs/jHbeWS2).

**Comment by TigerWalts** [comment]
I have seen this happen before. I believe it's caused in part by **Villager Names** and by another mod that alters how raids work. You can stop the error by disabling names for Illagers.

`villagerRules.json`
```
  "illagerEntityNames": false,
```
